FROM --platform=$BUILDPLATFORM golang:1.21 AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM

COPY . /src
WORKDIR /src
RUN go get -v ./...
RUN go vet -v ./...
RUN CGO_ENABLED=0 GO111MODULE=on go build

FROM --platform=$TARGETPLATFORM scratch
ARG TARGETPLATFORM
LABEL MAINTAINER="Jan Svoboda <svoboh@gmail.com>"

COPY --from=build /src/kubernetes-replicator /kubernetes-replicator

CMD ["/kubernetes-replicator"]
