apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.secretName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "secrets.dockerconfigjson" . | fromYaml | toJson | b64enc }}